### ISSUE TITLE
chisel github packaging system

### ISSUE THREAD

**Issue by Martoni** [freechipsproject/chisel-template#112]
I'm using chisel-template for each of my Chisel-project. Until now I published my packages locally to use them in other projects. It works but it's not easy to share Chisel project with this publish method.

So I started looking for the right way to publish «globally» [my packages](https://stackoverflow.com/questions/74239725/how-to-publish-chisel-package/74352289).

And I found a way with[ github packaging services](https://stackoverflow.com/a/74352289/4422957). I don't know if this is the right solution to publish globally Chisel packages but it seems to works.

So it could be interesting to add this option in chisel-template no ?

**Comment by schoeberl** [comment]
I think it is nice that GitHub offers this service. However, it is then restricted to GiHub users (maybe a non-issue as we are all members…). A more generic approach is to publish artifacts on Maven Central. It is more involved, but I took notes when I did this the first (and second) time and you can find it in an appendix of he Chisel book.

Cheers,
Martin

**Comment by Martoni** [comment]
Ok, I didn't know that github service was behind a "login-wall".

I will try Maven Central service for my repositories.

**Comment by Martoni** [comment]
@schoeberl I tryied with sonatype as you described it on your book but still stuck[ with 403 bug](https://github.com/Martoni/fpgamacro/issues/6). 
If you have an idea I'm interested :)
https://github.com/Martoni/fpgamacro/issues/6

**Comment by schoeberl** [comment]
No sorry, I have no idea want the reason is. I remember the first time it was quite involved with the account setup and manual OK. But I do not remember that error.
