### ISSUE TITLE
Template Cleanup failing

### ISSUE THREAD

**Issue by 5hayanB** [freechipsproject/chisel-template#115]
Template cleanup keeps failing after every re-run on Push changes.

![image](https://user-images.githubusercontent.com/91522269/222748714-fcdaa8d2-4e21-46ae-bfce-3de1a030468d.png)

Its also giving a warning
`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, ad-m/github-push-action@v0.6.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`

**Comment by esyvjlomh** [comment]
https://stackoverflow.com/a/75308228
I meet and solve this problem with the answer above.
