### ISSUE TITLE
Mill compile error

### ISSUE THREAD

**Issue by ilongshan** [freechipsproject/chisel-template#116]
using command "mill -i mill.scalalib.GenIdea/idea", it outputs the following error:

```
[info] compiling 1 Scala source to /Users/Test/test-mill/out/mill-build/compile.dest/classes ...
[error]  /Users/Test/test-mill/build.sc:25:23: not found: type Tests
[error]   object test extends Tests with ScalaTest {
[error]                       ^
[error] one error found
1 targets failed
compile Compilation failed
```

How to resolved it?

**Comment by Sevenqi7** [comment]
I solved this by downgrading the version of mill from 0.11.1 to 0.10.7.

**Comment by ilongshan** [comment]
@Sevenqi7 Thanks for you solution. Using the lower version can resolve this issue.

**Comment by f-zl** [comment]
In mill 0.11, replacing `Tests` by `ScalaTests` solves it.
https://github.com/com-lihaoyi/mill/discussions/2462#discussioncomment-7478637
