### ISSUE TITLE
when i run ./run-examples.sh GCD --backend-name verilator i get that error 

### ISSUE THREAD

**Issue by eahmedsalman** [freechipsproject/chisel-template#34]
verilated.o: In function VL_FINISH_MT(char const*, int, char const*)': verilated.cpp:(.text+0x7): undefined reference tovl_finish(char const, int, char const)'
collect2: error: ld returned 1 exit status
VGCD.mk:64: recipe for target 'VGCD' failed
make: Leaving directory '/home/salman/chisel-tutorial/test_run_dir/examples/GCD'
make: *** [VGCD] Error 1

Errors: 1: in the following tutorials
Tutorial GCD: throwable assertion failed:

**Comment by ucbjrl** [comment]
I believe this is due to a discrepancy in the verilator C++ harness generated by chisel-testers. We have a fix under review.

**Comment by eahmedsalman** [comment]
when will the fix be published and is their a work around on this error?

**Comment by ucbjrl** [comment]
I hope to have a fix out by the end of next week.

The work-around is to revert to verilator version 3.904.

**Comment by eahmedsalman** [comment]
thx

**Comment by ucbjrl** [comment]
I suspect this issue should have been filed against [chisel-tutorial](https://github.com/ucb-bar/chisel-tutorial) - there is no `run-examples.sh` in chisel-template.
In any case, the released version of chisel-testers supports verilator 3.922 and both chisel-tutorial and chisel-template work as advertised with the verilator backend.
