### ISSUE TITLE
move scalastyle config file to <project> when using intellij idea

### ISSUE THREAD

**Issue by zhutmost** [freechipsproject/chisel-template#39]
In IntelliJ IDEA, the scalastyle configuration file (e.g. `scalastyle-config.xml`) should be put in `<root>/project` or `<root>/.idea`, or it doesn't work. I'm not sure about other IDEs.

So maybe we can update the file hierarchy or the README file.

**Comment by jackkoenig** [comment]
@chick seems related to issues we've discussed previously with IntelliJ-style and repo-style disagreeing

**Comment by chick** [comment]
I think updating the README is a good idea. 
I am on the fence about updating the hierarchy, which to me would essentially mean that
a default intellij project folder would be part of the repo.  Maybe that's not so bad, but I think
we should be careful when promoting particular outside technology. I must disclose that I am an IntelliJ  user.
Any thoughts on the above, or is there another solution.

**Comment by edwardcwang** [comment]
Since not all Chisel users use intellJ I would agree to leave the hierarchy the same but document what should be done if using IntelliJ.

**Comment by chick** [comment]
@zhutmost if I clone the chisel-template repo and start up IntelliJ then add a scala file without the
recommended header I see the `Header does not match expected text` message, even though the chisel style guides are not in the ./project or ./.idea folders. I'm using 2018 CE and Pro editions. Could this have been an earlier problem

**Comment by zhutmost** [comment]
@chick I had a try. I am using IDEA 2018.2.4 Ultimate (the latest version).
![image](https://user-images.githubusercontent.com/20497382/46579388-0d539080-ca43-11e8-982e-fcd40fdbb046.png)
As depicted in the screenshot, the style-config.xml are put at the `<root>` dir.

**Comment by chick** [comment]
I think that means it's working OK as it is. If that's so can we close this?

**Comment by zhutmost** [comment]
Sorry for responding so late. you can close this issue at any time.
