### ISSUE TITLE
question about the /src/test/scala/gcd/GCDUnitTest.scala

### ISSUE THREAD

**Issue by PAIWANG94** [freechipsproject/chisel-template#42]
Hello,

In the GCDUnitTest.scala, there is a comment '' sbt 'testOnly examples.test.GCDTester'. However, in chisel-template repo, we don't have example folder. 

And I can run "sbt 'test:runMain gcd.GCDMain --generate-vcd-output on' " successfully . But how to run the GCDTester?

**Comment by ucbjrl** [comment]
The [README](https://github.com/freechipsproject/chisel-template/blob/release/README.md) explains one way to run the tester.
```bash
sbt 'testOnly gcd.GCDTester -- -z Basic'
```
will run tests in gcd.GCDTester containing the word `Basic`.

Additionally,
```bash
sbt 'testOnly gcd.GCDTester'
```
will run all `gcd.GCDTester` tests, and
```bash
sbt test
```
will run all tests.

Thanks for pointing out the out of date comment in `src/test/scala/gcd/GCDUnitTest.scala`. We'll update it.

**Comment by edwardcwang** [comment]
I think #43 fixed this - let me know if you still experience any issues.

**Comment by PAIWANG94** [comment]
Hi,
Thanks for you reply. But I got the error message when I use” testOnly gcd.GCDTester"



Pai Wang
Master of ECE Department 
University of Virginia

**Comment by edwardcwang** [comment]
Would it be possible for you to share the error message either here or in a new issue?

**Comment by PAIWANG94** [comment]
Hi,
It’s the same issue.I am testing the chisel-template. All the experiments can be run successfully except ”generate-vcd-output off”. So is it that  I miss something?

Pai Wang
Master of ECE Department 
University of Virginia
