### ISSUE TITLE
Dependencies broken?

### ISSUE THREAD

**Issue by shunshou** [freechipsproject/chisel-template#5]
I got a bunch of broken dependencies errors (chisel3, io testers) when I tried to use this template. I assume this'll be fixed for the actual Chisel 3 release? 
- As an aside, there should be some kind of documentation on getting a basic Chisel 3 project up and running if you don't want to run tests -- i.e. the equivalent of the old chiselMain but now with Driver rather than having to dig through rocket to see how it's done. 
- For people starting out / when dependencies are broken, what to do with your build.sbt to point to local Chisel/Firrtl stuff. 
- Also, an explanation on how to use Driver.elaborate followed by Firrtl stuff directly (rather than dumping Chirrtl to a file and then separately running Firrtl) would be nice for people just starting out, I'm sure.

**Comment by ucbjrl** [comment]
The current default branch for chisel-template is "master". This assumes you're doing development and have the requisite dependencies published locally.

I'm about to change the default branch to "release", which will use the released (and published) versions of the dependencies.

Your other comments are spot on and on my task list for the coming week.

**Comment by jackkoenig** [comment]
I'm closing this because it's stale but there is a point about talking about how to "run main" that needs to be addressed.
