### ISSUE TITLE
Making the repo as a github template project

### ISSUE THREAD

**Issue by amsharifian** [freechipsproject/chisel-template#79]
It's been a while that Github is offering an option to make an existing repository as a template project:

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

I think that's not a bad idea to enable this option for this repository, I've briefly listed the benefits that it offers:

* Start with no history and no reference to this repository.
* It's possible to run a **Template cleanup** workflow to override template-specific configurations, such as the sbt details. You can look at this example [Tempate-cleanup](https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.github/workflows/template-cleanup.yml)
* You can choose to include the directory structure and files from only the default/master branch 

There are more details here:
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

Github workflows:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

**Comment by jackkoenig** [comment]
This is a good idea, thanks for all of this information!

**Comment by jackkoenig** [comment]
Done, see https://github.com/freechipsproject/chisel-template/tree/main which is the new default branch.

**Comment by jackkoenig** [comment]
Thank you very much @amsharifian for the ideas, this is what we did!
